version: '3.7'

networks:
    web:
        external: true

services:
  xpense-api:
    build: .
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xpenseapi.rule=Host(`xpense-api.gredal.dev`)"
      - "traefik.http.routers.xpenseapi.tls=true"
      - "traefik.http.routers.xpenseapi.entrypoints=websecure"